addons:
  apt:
    sources:
    - sourceline: 'deb https://packages.atlassian.com/atlassian-sdk-deb stable contrib'
      key_url: 'https://packages.atlassian.com/api/gpg/key/public'
    packages:
    - atlassian-plugin-sdk

script: atlas-clean && atlas-compile && atlas-unit-test && atlas-integration-test
