language: java

# only build automatically for the master branch
branches:
  only:
  - master
# NB PRs should also be built automatically

# ensure Atlassian SDK is installed
addons:
  apt:
    sources:
    - sourceline: deb https://packages.atlassian.com/atlassian-sdk-deb stable contrib
      key_url: https://packages.atlassian.com/api/gpg/key/public
    packages:
    - atlassian-plugin-sdk -q
    
# test against all supported versions of Jira
env:
  - JIRA_VERSION=7.13.1
  - JIRA_VERSION=7.12.3
  - JIRA_VERSION=7.11.2
  - JIRA_VERSION=7.10.2
  - JIRA_VERSION=7.9.2
  - JIRA_VERSION=7.8.4
  - JIRA_VERSION=7.7.4
  - JIRA_VERSION=7.6.11
  - JIRA_VERSION=7.5.4
  - JIRA_VERSION=7.4.6

# skip the default install step defined for java
install: true

# define a custom build step
script: atlas-clean -q && travis_wait atlas-integration-test -q -Djira.version=$JIRA_VERSION

deploy:
  provider: releases
  api_key:
    secure: CLkdteUkUcKYPoEV+2dO/7IBR/HbMn3bsvMVz7IWKkrSh86IEsaW22CqjyqHlo+f4wI5Sug3fLvRcUBHgNsL4AA7ha1N2mH1kgOXiPgU2a/HGDEdeRMEJ7ngg/ilcDkeplx/aLVdDhKRKefmXqy+qJulkUinhXfTlyifKogYxH1Gt7bS6HXnHFCcNty/wXykjPx5IwE9/I2MXgg+dJiTrdEyTD+BDiXhIqqm4ORscf1SzbZ2Uqy9fWsJWWWm6YJMqB4eSHua3/EvOwVCTVc4BB/tXu18Ex3ex7epi2QF6YidI27jrUUOr8ccsSik7FBlabG8es7MvMTMlFAgOuOZQCgYQYs+0LPXuWkidzGRhtuMmp4ORWKZRTwT1AQ9wxlViH8HLwwhcOUl1cO2Tq7kLmgc0301Te3lp/GMMENlRy0yVJMKe6w8Jwrh4QSTeg2ie9HOqqzhm48oGCMGY083qzYxX2EDTrhliNRMZVM0+6KLnI5tGzDmiPp5PdVedNGHXeMjXgcg1uOqeUTNT05rZpbQ0iW8w4K0AmjjuwwsvnXx6Fg4ke/699uVPAEyQf181D/IYFVQ4wqKT+6t4ynfeWomVj5/xpMMZrp2NwfDUQQrmyp0Jmi+wlFiAuvJhin3oTxRB5btz6dm2ipI4ptzGNq5RAVU9FzvLt9bdeGEf1M=
  file_glob: true
  file: target/lgtm-jira-addon-*.jar
  skip_cleanup: true
  on:
    tags: true
  env: JIRA_VERSION=7.13.1
